---
- name: Apply {{ compliance_profile_id }} Benchmark security/compliance hardenning to the NEW RHEL 9 VM 
#  hosts: "{{ v_hostname_fqdn }}"
  hosts: all
  become: true
  become_method: sudo
  collections:
    - rhdemo.compliance

  tasks: 

    - name: Apply RHEL {{ ansible_distribution_major_version }}  {{ compliance_profile_id | default('CIS')}} Compliance Hardenning
      ansible.builtin.include_role:
        name: rhel{{ ansible_distribution_major_version }}-{{ compliance_profile_id | default('cis') | lower }}
        tasks_from: rhel{{ ansible_distribution_major_version }}-playbook-{{ compliance_profile_id | default('cid') | lower }}.yml

#    - name: Run Openscap Scan and Upload Reports to Satellite Server
#      include_role:
#        name: theforeman.foreman_scap_client

#    - name: Run Openscap Scan and Upload Reports to Gitlab
#      include_role:
#        name: openscap_scan_reports

#    - name: Remove Local Prov User and Create Automation svc account for continuous remediation
#      include_role:
#        name: rhel_post_config
#        tasks_from: 99_create_accounts.yml

